---
- name: create proxy container
  docker_container:
    name: proxy
    image: bitnami/nginx
    pull: true
    ports:
      - 80:8080
    volumes:
      - "{{ proxy_data }}/etc/nginx/conf.d:/opt/bitnami/nginx/conf/server_blocks:ro"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: add proxy to network
  community.general.docker_network:
    name: backend
    connected:
      - proxy
    appends: true
