---
- name: Create "proxy.logs" volume
  docker_volume:
    name: proxy.logs
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ proxy_data }}/var/log"
      map: "1001/0:@1001/@0"

- name: "Start Reverse-Proxy Server Container"
  docker_container:
    name: proxy
    image: jonasal/nginx-certbot
    pull: true
    env:
      CERTBOT_EMAIL: payson@paysonwallach.com
    ports:
      - 80:80
      - 443:443
    etc_hosts:
      host.docker.internal: host-gateway
    volumes:
      - "{{ proxy_data }}/etc/letsencrypt:/etc/letsencrypt"
      - "{{ proxy_data }}/etc/nginx/conf.d:/etc/nginx/conf.d"
      - "{{ proxy_data }}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "proxy.logs:/var/log/nginx"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: "Add Reverse-Proxy Server to Network"
  community.general.docker_network:
    name: backend
    connected:
      - proxy
    appends: true
