---
- name: create transmission container
  docker_container:
    image: lscr.io/linuxserver/transmission
    name: transmission
    pull: true
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: Europe/Zurich
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - "{{ transmission_data }}/config:/config"
      - "{{ transmission_data }}/downloads:/downloads"
      - "{{ transmission_data }}/watch:/watch"
    # ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    network_mode: host
