---
- name: Create "podcasts" volume
  docker_volume:
    name: podcasts
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ podcasts_data }}/app"
      map: "1001/0:@1001/@0"

- name: podcasts.app
  docker_container:
    name: podcasts.app
    image: harbour.paysonwallach.com/paysonwallach/podcasts
    pull: false
    volumes:
      - "podcasts:/srv"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: podcasts.proxy
  docker_container:
    name: podcasts.proxy
    image: bitnami/nginx
    pull: true
    volumes:
      - "{{ podcasts_data }}:/var/www/podcasts.paysonwallach.com:ro"
      - "{{ podcasts_data }}/proxy/etc/nginx/conf.d/podcasts.paysonwallach.com.conf:/opt/bitnami/nginx/conf/server_blocks/podcasts.paysonwallach.com.conf:ro"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: 'Add "podcasts" to Network'
  community.general.docker_network:
    name: backend
    connected:
      - podcasts.app
      - podcasts.proxy
    appends: true
