---
- name: plex
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    env:
      PUID: "1001"
      GUID: "1001"
      VERSION: docker
    volumes:
      - "{{ home_dir }}/plex/config:/config"
      - "/storage/movies:/data/movies"
      - "/storage/shows:/data/shows"
      - "/storage/share:/storage/share"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    network_mode: host
