#!/usr/bin/env bash

set -euo pipefail

CONTAINER=$1

if [[ -z $CONTAINER ]]; then
  echo "No container specified"
  exit 1
fi

if [[ "$(docker ps -aq -f name=^/"$CONTAINER"$ 2>/dev/null)" == "" ]]; then

  CONTAINER="$(docker-compose ps "$CONTAINER" 2>/dev/null | awk 'END {print $1}')"

  if [[ -z $CONTAINER ]]; then
    echo "Container \"$1\" does not exist, exiting."
    exit 1
  fi
fi

LOG=$(docker inspect -f '{{.LogPath}}' "$CONTAINER" 2>/dev/null)
truncate -s 0 "$LOG"
