---
- name: Determine whether borgmatic can be installed as a package
  set_fact:
    install_borgmatic_as_package: "{{ False if ( ansible_distribution == 'Debian' and
     ( ansible_distribution_release == 'stretch' or ansible_distribution_release == 'buster' )
     or ansible_distribution == 'Ubuntu' and
     ( ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic' )
     or ansible_distribution == 'Linux Mint' and ansible_distribution_major_version <= '19' ) else True }}"
  tags: borgmatic
- name: Install borgmatic package
  when: install_borgmatic_as_package
  apt:
    pkg:
      - borgmatic
- name: Install borgmatic via pip
  when: not install_borgmatic_as_package
  include_role:
    name: baztian.pip_venv
  vars:
      pkg: borgmatic
      version: "{{ borgmatic_unpackaged_version }}"
  tags: borgmatic
