---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- import_tasks: borg-install.yml
- import_tasks: borgmatic-install.yml
- import_tasks: borgmatic-config.yml
- import_tasks: borgmatic-job.yml
