---
- name: git.app
  docker_container:
    name: git.app
    image: pass-server
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ git_data }}/data/.htpasswd:/etc/nginx/.htpasswd:ro"
      - "{{ git_data }}/data/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ git_data }}/repositories:/repositories"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: git.proxy
  docker_container:
    name: git.proxy
    image: bitnami/nginx
    pull: true
    volumes:
      - "{{ git_data }}/repositories:/var/www/git:ro"
      - "{{ git_data }}/proxy/etc/nginx/conf.d/git.paysonwallach.com.conf:/opt/bitnami/nginx/conf/server_blocks/git.paysonwallach.com.conf:ro"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: "Add Pass to Network"
  community.general.docker_network:
    name: backend
    connected:
      - git.app
      - git.proxy
    appends: true
