---
- name: Create "nextcloud.database" volume
  docker_volume:
    name: nextcloud.database
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ nextcloud_data }}/data/database"
      map: "1001/70:@1001/@70"

- name: Create "nextcloud.site" volume
  docker_volume:
    name: nextcloud.site
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ nextcloud_data }}/data/html"
      map: "1001/33:@1001/@33"

- name: Create "nextcloud.theme" volume
  docker_volume:
    name: nextcloud.theme
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ nextcloud_data }}/theme"
      map: "1001/33:@1001/@33"

- name: database
  docker_container:
    name: nextcloud.database
    image: postgres:13-alpine
    pull: true
    env:
      POSTGRES_DB: "nexcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "DECIMETER-HARDNESS-CONTENTS-marmalade"
    volumes:
      - "nextcloud.database:/var/lib/postgresql/data"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: nextcloud.app
  docker_container:
    name: nextcloud.app
    image: nextcloud:fpm
    pull: true
    env:
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "animosity-revivable-perplexed-subtext"
      POSTGRES_HOST: "nextcloud.database"
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "DECIMETER-HARDNESS-CONTENTS-marmalade"
      SMTP_HOST: "smtp.mailbox.org"
      SMTP_SECURE: "tls"
      SMTP_PORT: "587"
      SMTP_NAME: "payson@paysonwallach.com"
      SMTP_PASSWORD: "UNSTEADY-reverence-UNWANTED-CR3ATURE"
    volumes:
      - "nextcloud.site:/var/www/html"
      - "nextcloud.theme:/var/www/html/themes"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: nextcloud.proxy
  docker_container:
    name: nextcloud.proxy
    image: bitnami/nginx
    pull: true
    volumes:
      - "{{ nextcloud_data }}/data/html:/var/www/cloud.paysonwallach.com:ro"
      - "{{ nextcloud_data }}/theme:/var/www/cloud.paysonwallach.com/themes:ro"
      - "{{ nextcloud_data }}/proxy/etc/nginx/conf.d/cloud.paysonwallach.com.conf:/opt/bitnami/nginx/conf/server_blocks/cloud.paysonwallach.com.conf:ro"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: 'Add "nextcloud" to Network'
  community.general.docker_network:
    name: backend
    connected:
      - nextcloud.app
      - nextcloud.database
      - nextcloud.proxy
    appends: true
