@ansible_home = "/home/vagrant/ansible"

Vagrant.require_version ">= 2.2.2"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "cloud-testing"
  config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 9283, host: 9283, host_ip: "127.0.0.1"

  config.vm.synced_folder ".", "#{@ansible_home}"
  config.vm.provision "shell", inline: "chown vagrant:vagrant #{@ansible_home}"

  config.vm.provision "ansible", run: "always" do |ansible|
    # ansible.compatibility_mode = "2.0"
    # ansible.install_mode = "pip"

    ansible.galaxy_role_file = "requirements.yml"
    ansible.playbook = "cloud.yml"

    # ansible.become = true
  end
end
