---
- name: Create "pass.data" volume
  docker_volume:
    name: pass.data
    driver: lebokus/bindfs:latest
    driver_options:
      sourcePath: "{{ pass_data }}/www"
      map: "1001/0:@1001/@0"

- name: "Start Pass Container"
  docker_container:
    name: pass
    image: pass-server
    volumes:
      - "{{ pass_data }}/etc/nginx/.htpasswd:/etc/nginx/.htpasswd:ro"
      - "{{ pass_data }}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "pass.data:/var/www/pass"
    container_default_behavior: no_defaults
    restart_policy: unless-stopped

- name: "Add Pass to Network"
  community.general.docker_network:
    name: backend
    connected:
      - pass
    appends: true
